In [10]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

Importing the Dependencies

In [11]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [12]:
# loading the dataset to a Pandas DataFrame
credit_card_data = pd.read_csv('/content/creditcard.csv')

In [13]:
# First Five rows of the Dataset
credit_card_data.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0.0
1,0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0.0
2,1,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0.0
3,1,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0.0
4,2,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0.0

In [14]:
credit_card_data.tail()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
31775,36510,1.497714,-0.874208,0.004261,-1.537368,-1.044513,-0.733905,-0.644635,-0.186510,-2.380495,...,-0.527761,-1.248016,0.145825,-0.061193,0.250252,-0.526898,0.003761,0.007950,24.90,0.0
31776,36512,-0.407854,0.940336,1.533733,-0.018123,-0.219400,-0.934602,0.597172,0.024610,-0.151850,...,-0.247570,-0.725830,-0.006221,0.322366,-0.249413,0.076587,0.255380,0.117340,1.79,0.0
31777,36513,-0.434226,-3.705556,0.194223,0.139216,-2.066818,1.220137,-0.278115,0.281452,-0.161302,...,0.620431,0.040315,-0.690176,-0.226844,-0.123369,-0.291412,-0.080514,0.155457,861.12,0.0
31778,36513,-0.274278,1.004565,1.336430,-0.164777,0.404935,-0.418731,0.853252,-0.148772,-0.546969,...,-0.277437,-0.579135,-0.097793,-0.037926,-0.157882,0.044814,0.078376,-0.137035,9.72,0.0
31779,36513,1.295137,0.096775,0.348134,0.629896,-0.172700,-0.154350,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [15]:
# dataset information
credit_card_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 31780 entries, 0 to 31779
Data columns (total 31 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Time    31780 non-null  int64
 1   V1      31780 non-null  float64
 2   V2      31780 non-null  float64
 3   V3      31780 non-null  float64
 4   V4      31780 non-null  float64
 5   V5      31780 non-null  float64
 6   V6      31780 non-null  float64
 7   V7      31779 non-null  float64
 8   V8      31779 non-null  float64
 9   V9      31779 non-null  float64
 10  V10     31779 non-null  float64
 11  V11     31779 non-null  float64
 12  V12     31779 non-null  float64
 13  V13     31779 non-null  float64
 14  V14     31779 non-null  float64
 15  V15     31779 non-null  float64
 16  V16     31779 non-null  float64
 17  V17     31779 non-null  float64
 18  V18     31779 non-null  float64
 19  V19     31779 non-null  float64
 20  V20     31779 non-null  float64
 21  V21     31779 non-null  float64
 22  V22     31779 non-null  float64
 23  V23     31779 non-null  float64
 24  V24     31779 non-null  float64
 25  V25     31779 non-null  float64
 26  V26     31779 non-null  float64
 27  V27     31779 non-null  float64
 28  V28     31779 non-null  float64
 29  Amount  31779 non-null  float64
 30  Class   31779 non-null  float64
dtypes: float64(30), int64(1)
memory usage: 7.5 MB

In [16]:
# checking the numberv of missing values in each column
credit_card_data.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        1
V8        1
V9        1
V10       1
V11       1
V12       1
V13       1
V14       1
V15       1
V16       1
V17       1
V18       1
V19       1
V20       1
V21       1
V22       1
V23       1
V24       1
V25       1
V26       1
V27       1
V28       1
Amount    1
Class     1
dtype: int64

In [17]:
# distribution of legit transactions & fraudulent transaction
credit_card_data['Class'].value_counts()

Class
0.0    31677
1.0      102
Name: count, dtype: int64

This Dataset is highly unbalanced

0 --> Normal Transaction

1 --> Fraudulent Transaction

In [18]:
# sepearting the data for analysis
legit = credit_card_data[credit_card_data.Class == 0]
fraud = credit_card_data[credit_card_data.Class == 1]

In [19]:
print(legit.shape)
print(fraud.shape)

(31677, 31)
(102, 31)

In [20]:
# statistical measures of the data
legit.Amount.describe()

count    31677.000000
mean        81.082407
std        223.072655
min          0.000000
25%          6.870000
50%         20.000000
75%         73.610000
max       7879.420000
Name: Amount, dtype: float64

In [21]:
fraud.Amount.describe()

count     102.000000
mean       91.237451
std       248.270971
min         0.000000
25%         1.000000
50%         3.440000
75%        99.990000
max      1809.680000
Name: Amount, dtype: float64

In [22]:
# compare the values for both transactions
credit_card_data.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0.0,22335.407141,-0.188381,0.085855,0.759238,0.192821,-0.192581,0.095930,-0.095538,0.019413,0.324683,...,0.041991,-0.03532,-0.118406,-0.039544,0.009212,0.133785,0.022140,0.010340,0.003013,81.082407
1.0,20334.872549,-7.761095,5.946853,-11.035230,5.926171,-5.529543,-2.295415,-7.767215,3.904551,-2.997290,...,0.679987,0.64190,-0.352131,-0.317568,-0.241053,0.314412,0.177056,0.811372,0.118708,91.237451

Under-Sampling

Build a same dataset containing similar distribution of normal transactions and Fraudulent Transactions

Number of Fraudulent Transactions --> 492

In [23]:
legit_sample = legit.sample(n=492)

Concatenating two DataFrames

In [24]:
new_dataset = pd.concat([legit_sample, fraud], axis=0)

In [25]:
new_dataset.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
8443,11326,-0.574412,1.077251,2.946749,2.596946,-0.072033,0.900387,-0.134659,0.303339,0.617274,...,-0.119434,0.072215,-0.125845,0.024788,-0.270748,0.025602,0.131290,0.116322,0.00,0.0
7828,10911,1.159685,0.379515,1.328155,2.721188,-0.237186,0.701321,-0.573907,0.071107,1.287667,...,-0.270493,-0.353322,-0.072757,-0.496933,0.417240,-0.034843,0.019410,0.025652,15.13,0.0
14493,25675,0.964839,-0.052220,0.449664,1.542959,-0.372619,-0.334209,0.219721,-0.079995,0.208935,...,-0.020998,-0.017011,-0.106861,0.421835,0.596585,-0.343290,0.025205,0.035869,100.00,0.0
26974,34329,-1.224766,0.902002,2.131423,1.608077,-0.463374,0.860830,-0.065049,0.490246,0.587397,...,-0.352430,-0.395460,-0.033136,0.111703,-0.033922,-0.423482,-0.101667,-0.086883,22.99,0.0
1900,1467,-1.629826,1.326529,0.906349,-0.800461,-0.283720,-0.383247,0.201000,0.585984,0.253948,...,-0.197779,-0.385304,-0.066693,0.022864,0.141284,0.385286,0.250911,0.192462,5.00,0.0

In [26]:
new_dataset.tail()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
30398,35906,-3.519030,4.140867,-3.628202,5.505672,-4.057463,-0.905945,-6.652031,2.634524,-4.679402,...,1.582556,0.778710,-0.135707,-0.004278,0.032706,0.362014,0.900925,0.554897,9.13,1.0
30442,35926,-3.896583,4.518355,-4.454027,5.547453,-4.121459,-1.163407,-6.805053,2.928356,-4.917130,...,1.691042,0.920021,-0.151104,0.011007,0.080303,0.412191,0.635789,0.501050,4.56,1.0
30473,35942,-4.194074,4.382897,-5.118363,4.455230,-4.812621,-1.224645,-7.281328,3.332250,-3.679659,...,1.550473,0.614573,0.028521,0.013704,-0.149512,-0.131687,0.473934,0.473757,14.46,1.0
30496,35953,-4.844372,5.649439,-6.730396,5.252842,-4.409566,-1.740767,-6.311699,3.449167,-5.416284,...,1.194888,-0.845753,0.190674,-0.216443,-0.325033,-0.270328,0.210214,0.391855,111.70,1.0
31002,36170,-5.685013,5.776516,-7.064977,5.902715,-4.715564,-1.755633,-6.958679,3.877795,-5.541529,...,1.128641,-0.962960,-0.110045,-0.177733,-0.089175,-0.049447,0.303445,0.219380,111.70,1.0

In [27]:
new_dataset['Class'].value_counts()

Class
0.0    492
1.0    102
Name: count, dtype: int64

In [28]:
new_dataset.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0.0,21753.475610,-0.179029,0.098879,0.674404,0.278730,-0.212560,0.124594,-0.132869,0.009795,0.355158,...,0.057242,-0.047217,-0.126295,-0.051206,0.028988,0.142004,0.019419,-0.003173,-0.031105,82.260081
1.0,20334.872549,-7.761095,5.946853,-11.035230,5.926171,-5.529543,-2.295415,-7.767215,3.904551,-2.997290,...,0.679987,0.641900,-0.352131,-0.317568,-0.241053,0.314412,0.177056,0.811372,0.118708,91.237451

Splitting the data into Features & Targets

In [29]:
X = new_dataset.drop(columns='Class', axis=1)
Y = new_dataset['Class']

In [30]:
print(X)

        Time        V1        V2        V3        V4        V5        V6  \
8443   11326 -0.574412  1.077251  2.946749  2.596946 -0.072033  0.900387
7828   10911  1.159685  0.379515  1.328155  2.721188 -0.237186  0.701321
14493  25675  0.964839 -0.052220  0.449664  1.542959 -0.372619 -0.334209
26974  34329 -1.224766  0.902002  2.131423  1.608077 -0.463374  0.860830
1900    1467 -1.629826  1.326529  0.906349 -0.800461 -0.283720 -0.383247
...      ...       ...       ...       ...       ...       ...       ...
30398  35906 -3.519030  4.140867 -3.628202  5.505672 -4.057463 -0.905945
30442  35926 -3.896583  4.518355 -4.454027  5.547453 -4.121459 -1.163407
30473  35942 -4.194074  4.382897 -5.118363  4.455230 -4.812621 -1.224645
30496  35953 -4.844372  5.649439 -6.730396  5.252842 -4.409566 -1.740767
31002  36170 -5.685013  5.776516 -7.064977  5.902715 -4.715564 -1.755633

             V7        V8        V9  ...       V20       V21       V22  \
8443  -0.134659  0.303339  0.617274  ... -0.056263 -0.119434  0.072215
7828  -0.573907  0.071107  1.287667  ... -0.080468 -0.270493 -0.353322
14493  0.219721 -0.079995  0.208935  ...  0.005891 -0.020998 -0.017011
26974 -0.065049  0.490246  0.587397  ...  0.093876 -0.352430 -0.395460
1900   0.201000  0.585984  0.253948  ...  0.080721 -0.197779 -0.385304
...         ...       ...       ...  ...       ...       ...       ...
30398 -6.652031  2.634524 -4.679402  ...  0.898723  1.582556  0.778710
30442 -6.805053  2.928356 -4.917130  ...  0.757287  1.691042  0.920021
30473 -7.281328  3.332250 -3.679659  ...  0.579098  1.550473  0.614573
30496 -6.311699  3.449167 -5.416284  ...  0.284555  1.194888 -0.845753
31002 -6.958679  3.877795 -5.541529  ...  0.299489  1.128641 -0.962960

            V23       V24       V25       V26       V27       V28  Amount
8443  -0.125845  0.024788 -0.270748  0.025602  0.131290  0.116322    0.00
7828  -0.072757 -0.496933  0.417240 -0.034843  0.019410  0.025652   15.13
14493 -0.106861  0.421835  0.596585 -0.343290  0.025205  0.035869  100.00
26974 -0.033136  0.111703 -0.033922 -0.423482 -0.101667 -0.086883   22.99
1900  -0.066693  0.022864  0.141284  0.385286  0.250911  0.192462    5.00
...         ...       ...       ...       ...       ...       ...     ...
30398 -0.135707 -0.004278  0.032706  0.362014  0.900925  0.554897    9.13
30442 -0.151104  0.011007  0.080303  0.412191  0.635789  0.501050    4.56
30473  0.028521  0.013704 -0.149512 -0.131687  0.473934  0.473757   14.46
30496  0.190674 -0.216443 -0.325033 -0.270328  0.210214  0.391855  111.70
31002 -0.110045 -0.177733 -0.089175 -0.049447  0.303445  0.219380  111.70

[594 rows x 30 columns]

In [31]:
print(Y)

8443     0.0
7828     0.0
14493    0.0
26974    0.0
1900     0.0
        ...
30398    1.0
30442    1.0
30473    1.0
30496    1.0
31002    1.0
Name: Class, Length: 594, dtype: float64

Split the data into Traning data & Testing data

In [32]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, stratify=Y, random_state=2)

In [33]:
print(X.shape, X_train.shape, X_test.shape)

(594, 30) (475, 30) (119, 30)

Model Training

Logistic Regression

In [34]:
model = LogisticRegression()

In [35]:
# training the Logistic Regression Model with Traning Data
model.fit(X_train, Y_train)

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

Model Evaluation

Accuracy Score

In [37]:
# accuracy on training data
X_train_prediction = model.predict(X_train)
training_data_accuracy = accuracy_score(X_train_prediction, Y_train)

In [38]:
print('Accuracy on Training data: ', training_data_accuracy)

Accuracy on Training data:  0.9873684210526316

In [39]:
# accuracy on test data
X_test_prediction = model.predict(X_test)
test_data_accuracy = accuracy_score(X_test_prediction, Y_test)

In [40]:
print('Accuracy on Test data: ', test_data_accuracy)

Accuracy on Test data:  0.9831932773109243